/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionApplicationView {
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'marksheet10' : [] | [ExternalBlob],
  'marksheet12' : [] | [ExternalBlob],
  'name' : string,
  'submittedAt' : Timestamp,
  'aadhaar' : [] | [ExternalBlob],
  'email' : string,
  'phone' : string,
  'photo' : [] | [ExternalBlob],
  'passCertificate' : [] | [ExternalBlob],
  'courseId' : CourseId,
}
export type ApplicationId = bigint;
export interface ApplicationInput {
  'marksheet10' : [] | [ExternalBlob],
  'marksheet12' : [] | [ExternalBlob],
  'name' : string,
  'aadhaar' : [] | [ExternalBlob],
  'email' : string,
  'phone' : string,
  'photo' : [] | [ExternalBlob],
  'passCertificate' : [] | [ExternalBlob],
  'courseId' : CourseId,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AttendanceId = bigint;
export interface AttendanceRecord {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : string,
  'markedAt' : Timestamp,
}
export type AttendanceStatus = { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export interface AttendanceSummary {
  'total' : bigint,
  'present' : bigint,
  'late' : bigint,
  'absent' : bigint,
}
export interface Certificate {
  'id' : CertificateId,
  'studentId' : StudentId,
  'studentName' : string,
  'issuedAt' : Timestamp,
  'courseName' : string,
  'certificateCode' : string,
  'courseId' : CourseId,
}
export type CertificateId = bigint;
export interface Course {
  'id' : CourseId,
  'name' : string,
  'durationMonths' : bigint,
  'description' : string,
  'benefits' : Array<string>,
}
export type CourseId = string;
export type ExternalBlob = Uint8Array;
export type LeaveRequestId = bigint;
export interface LeaveRequestInput {
  'endDate' : string,
  'startDate' : string,
  'reason' : string,
}
export interface LeaveRequestView {
  'id' : LeaveRequestId,
  'studentId' : StudentId,
  'endDate' : string,
  'leaveStatus' : LeaveStatus,
  'submittedAt' : Timestamp,
  'respondedAt' : [] | [Timestamp],
  'startDate' : string,
  'reason' : string,
}
export type LeaveStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Notice {
  'id' : NoticeId,
  'title' : string,
  'postedAt' : Timestamp,
  'content' : string,
}
export type NoticeId = bigint;
export type StudentId = bigint;
export interface StudentInput {
  'username' : string,
  'applicationId' : [] | [ApplicationId],
  'password' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
  'courseId' : CourseId,
}
export interface StudentUpdateInput {
  'enrolled' : [] | [boolean],
  'name' : [] | [string],
  'email' : [] | [string],
  'phone' : [] | [string],
  'courseId' : [] | [CourseId],
}
export interface StudentView {
  'id' : StudentId,
  'username' : string,
  'enrolled' : boolean,
  'applicationId' : [] | [ApplicationId],
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'phone' : string,
  'profilePicture' : [] | [string],
  'courseId' : CourseId,
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminCreateStudent' : ActorMethod<
    [string, string, StudentInput],
    StudentView
  >,
  'adminDeleteApplication' : ActorMethod<
    [string, string, ApplicationId],
    boolean
  >,
  'adminDeleteCertificate' : ActorMethod<
    [string, string, CertificateId],
    boolean
  >,
  'adminDeleteLeaveRequest' : ActorMethod<
    [string, string, LeaveRequestId],
    boolean
  >,
  'adminDeleteNotice' : ActorMethod<[string, string, NoticeId], boolean>,
  'adminDeleteStudent' : ActorMethod<[string, string, StudentId], boolean>,
  'adminGetStudent' : ActorMethod<
    [string, string, StudentId],
    [] | [StudentView]
  >,
  'adminGetStudentAttendance' : ActorMethod<
    [string, string, StudentId],
    Array<AttendanceRecord>
  >,
  'adminIssueCertificate' : ActorMethod<
    [string, string, StudentId],
    Certificate
  >,
  'adminListApplications' : ActorMethod<
    [string, string],
    Array<AdmissionApplicationView>
  >,
  'adminListCertificates' : ActorMethod<[string, string], Array<Certificate>>,
  'adminListLeaveRequests' : ActorMethod<
    [string, string],
    Array<LeaveRequestView>
  >,
  'adminListStudents' : ActorMethod<[string, string], Array<StudentView>>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'adminMarkAttendance' : ActorMethod<
    [string, string, StudentId, string, AttendanceStatus],
    AttendanceRecord
  >,
  'adminPostNotice' : ActorMethod<[string, string, string, string], Notice>,
  'adminRespondLeaveRequest' : ActorMethod<
    [string, string, LeaveRequestId, LeaveStatus],
    boolean
  >,
  'adminUpdateApplicationStatus' : ActorMethod<
    [string, string, ApplicationId, ApplicationStatus],
    boolean
  >,
  'adminUpdateStudent' : ActorMethod<
    [string, string, StudentId, StudentUpdateInput],
    boolean
  >,
  'adminUpdateStudentProfilePicture' : ActorMethod<
    [string, string, StudentId, string],
    boolean
  >,
  'getApplication' : ActorMethod<
    [ApplicationId],
    [] | [AdmissionApplicationView]
  >,
  'getCertificate' : ActorMethod<[CertificateId], [] | [Certificate]>,
  'getCourse' : ActorMethod<[string], [] | [Course]>,
  'getMyAttendance' : ActorMethod<
    [StudentId],
    { 'records' : Array<AttendanceRecord>, 'summary' : AttendanceSummary }
  >,
  'getMyLeaveRequests' : ActorMethod<[StudentId], Array<LeaveRequestView>>,
  'getNotice' : ActorMethod<[NoticeId], [] | [Notice]>,
  'getStudentCertificates' : ActorMethod<[StudentId], Array<Certificate>>,
  'getStudentDashboard' : ActorMethod<[StudentId], [] | [StudentView]>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'listNotices' : ActorMethod<[], Array<Notice>>,
  'studentLogin' : ActorMethod<[string, string], [] | [StudentView]>,
  'studentUpdateProfilePicture' : ActorMethod<[StudentId, string], boolean>,
  'submitApplication' : ActorMethod<
    [ApplicationInput],
    AdmissionApplicationView
  >,
  'submitLeaveRequest' : ActorMethod<
    [StudentId, LeaveRequestInput],
    LeaveRequestView
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];