/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ApplicationId = IDL.Nat;
export const CourseId = IDL.Text;
export const StudentInput = IDL.Record({
  'username' : IDL.Text,
  'applicationId' : IDL.Opt(ApplicationId),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'courseId' : CourseId,
});
export const StudentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const StudentView = IDL.Record({
  'id' : StudentId,
  'username' : IDL.Text,
  'enrolled' : IDL.Bool,
  'applicationId' : IDL.Opt(ApplicationId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'profilePicture' : IDL.Opt(IDL.Text),
  'courseId' : CourseId,
});
export const CertificateId = IDL.Nat;
export const LeaveRequestId = IDL.Nat;
export const NoticeId = IDL.Nat;
export const AttendanceId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : IDL.Text,
  'markedAt' : Timestamp,
});
export const Certificate = IDL.Record({
  'id' : CertificateId,
  'studentId' : StudentId,
  'studentName' : IDL.Text,
  'issuedAt' : Timestamp,
  'courseName' : IDL.Text,
  'certificateCode' : IDL.Text,
  'courseId' : CourseId,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdmissionApplicationView = IDL.Record({
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'marksheet10' : IDL.Opt(ExternalBlob),
  'marksheet12' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'aadhaar' : IDL.Opt(ExternalBlob),
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'passCertificate' : IDL.Opt(ExternalBlob),
  'courseId' : CourseId,
});
export const LeaveStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LeaveRequestView = IDL.Record({
  'id' : LeaveRequestId,
  'studentId' : StudentId,
  'endDate' : IDL.Text,
  'leaveStatus' : LeaveStatus,
  'submittedAt' : Timestamp,
  'respondedAt' : IDL.Opt(Timestamp),
  'startDate' : IDL.Text,
  'reason' : IDL.Text,
});
export const Notice = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'postedAt' : Timestamp,
  'content' : IDL.Text,
});
export const StudentUpdateInput = IDL.Record({
  'enrolled' : IDL.Opt(IDL.Bool),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'courseId' : IDL.Opt(CourseId),
});
export const Course = IDL.Record({
  'id' : CourseId,
  'name' : IDL.Text,
  'durationMonths' : IDL.Nat,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const AttendanceSummary = IDL.Record({
  'total' : IDL.Nat,
  'present' : IDL.Nat,
  'late' : IDL.Nat,
  'absent' : IDL.Nat,
});
export const ApplicationInput = IDL.Record({
  'marksheet10' : IDL.Opt(ExternalBlob),
  'marksheet12' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'aadhaar' : IDL.Opt(ExternalBlob),
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'passCertificate' : IDL.Opt(ExternalBlob),
  'courseId' : CourseId,
});
export const LeaveRequestInput = IDL.Record({
  'endDate' : IDL.Text,
  'startDate' : IDL.Text,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminCreateStudent' : IDL.Func(
      [IDL.Text, IDL.Text, StudentInput],
      [StudentView],
      [],
    ),
  'adminDeleteApplication' : IDL.Func(
      [IDL.Text, IDL.Text, ApplicationId],
      [IDL.Bool],
      [],
    ),
  'adminDeleteCertificate' : IDL.Func(
      [IDL.Text, IDL.Text, CertificateId],
      [IDL.Bool],
      [],
    ),
  'adminDeleteLeaveRequest' : IDL.Func(
      [IDL.Text, IDL.Text, LeaveRequestId],
      [IDL.Bool],
      [],
    ),
  'adminDeleteNotice' : IDL.Func(
      [IDL.Text, IDL.Text, NoticeId],
      [IDL.Bool],
      [],
    ),
  'adminDeleteStudent' : IDL.Func(
      [IDL.Text, IDL.Text, StudentId],
      [IDL.Bool],
      [],
    ),
  'adminGetStudent' : IDL.Func(
      [IDL.Text, IDL.Text, StudentId],
      [IDL.Opt(StudentView)],
      ['query'],
    ),
  'adminGetStudentAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, StudentId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'adminIssueCertificate' : IDL.Func(
      [IDL.Text, IDL.Text, StudentId],
      [Certificate],
      [],
    ),
  'adminListApplications' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AdmissionApplicationView)],
      [],
    ),
  'adminListCertificates' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Certificate)],
      ['query'],
    ),
  'adminListLeaveRequests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(LeaveRequestView)],
      ['query'],
    ),
  'adminListStudents' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(StudentView)],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminMarkAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, StudentId, IDL.Text, AttendanceStatus],
      [AttendanceRecord],
      [],
    ),
  'adminPostNotice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Notice],
      [],
    ),
  'adminRespondLeaveRequest' : IDL.Func(
      [IDL.Text, IDL.Text, LeaveRequestId, LeaveStatus],
      [IDL.Bool],
      [],
    ),
  'adminUpdateApplicationStatus' : IDL.Func(
      [IDL.Text, IDL.Text, ApplicationId, ApplicationStatus],
      [IDL.Bool],
      [],
    ),
  'adminUpdateStudent' : IDL.Func(
      [IDL.Text, IDL.Text, StudentId, StudentUpdateInput],
      [IDL.Bool],
      [],
    ),
  'adminUpdateStudentProfilePicture' : IDL.Func(
      [IDL.Text, IDL.Text, StudentId, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'getApplication' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(AdmissionApplicationView)],
      ['query'],
    ),
  'getCertificate' : IDL.Func(
      [CertificateId],
      [IDL.Opt(Certificate)],
      ['query'],
    ),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
  'getMyAttendance' : IDL.Func(
      [StudentId],
      [
        IDL.Record({
          'records' : IDL.Vec(AttendanceRecord),
          'summary' : AttendanceSummary,
        }),
      ],
      ['query'],
    ),
  'getMyLeaveRequests' : IDL.Func(
      [StudentId],
      [IDL.Vec(LeaveRequestView)],
      ['query'],
    ),
  'getNotice' : IDL.Func([NoticeId], [IDL.Opt(Notice)], ['query']),
  'getStudentCertificates' : IDL.Func(
      [StudentId],
      [IDL.Vec(Certificate)],
      ['query'],
    ),
  'getStudentDashboard' : IDL.Func(
      [StudentId],
      [IDL.Opt(StudentView)],
      ['query'],
    ),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'listNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(StudentView)], []),
  'studentUpdateProfilePicture' : IDL.Func(
      [StudentId, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'submitApplication' : IDL.Func(
      [ApplicationInput],
      [AdmissionApplicationView],
      [],
    ),
  'submitLeaveRequest' : IDL.Func(
      [StudentId, LeaveRequestInput],
      [LeaveRequestView],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ApplicationId = IDL.Nat;
  const CourseId = IDL.Text;
  const StudentInput = IDL.Record({
    'username' : IDL.Text,
    'applicationId' : IDL.Opt(ApplicationId),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'courseId' : CourseId,
  });
  const StudentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const StudentView = IDL.Record({
    'id' : StudentId,
    'username' : IDL.Text,
    'enrolled' : IDL.Bool,
    'applicationId' : IDL.Opt(ApplicationId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'profilePicture' : IDL.Opt(IDL.Text),
    'courseId' : CourseId,
  });
  const CertificateId = IDL.Nat;
  const LeaveRequestId = IDL.Nat;
  const NoticeId = IDL.Nat;
  const AttendanceId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : IDL.Text,
    'markedAt' : Timestamp,
  });
  const Certificate = IDL.Record({
    'id' : CertificateId,
    'studentId' : StudentId,
    'studentName' : IDL.Text,
    'issuedAt' : Timestamp,
    'courseName' : IDL.Text,
    'certificateCode' : IDL.Text,
    'courseId' : CourseId,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdmissionApplicationView = IDL.Record({
    'id' : ApplicationId,
    'status' : ApplicationStatus,
    'marksheet10' : IDL.Opt(ExternalBlob),
    'marksheet12' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'aadhaar' : IDL.Opt(ExternalBlob),
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'passCertificate' : IDL.Opt(ExternalBlob),
    'courseId' : CourseId,
  });
  const LeaveStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LeaveRequestView = IDL.Record({
    'id' : LeaveRequestId,
    'studentId' : StudentId,
    'endDate' : IDL.Text,
    'leaveStatus' : LeaveStatus,
    'submittedAt' : Timestamp,
    'respondedAt' : IDL.Opt(Timestamp),
    'startDate' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Notice = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'postedAt' : Timestamp,
    'content' : IDL.Text,
  });
  const StudentUpdateInput = IDL.Record({
    'enrolled' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'courseId' : IDL.Opt(CourseId),
  });
  const Course = IDL.Record({
    'id' : CourseId,
    'name' : IDL.Text,
    'durationMonths' : IDL.Nat,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const AttendanceSummary = IDL.Record({
    'total' : IDL.Nat,
    'present' : IDL.Nat,
    'late' : IDL.Nat,
    'absent' : IDL.Nat,
  });
  const ApplicationInput = IDL.Record({
    'marksheet10' : IDL.Opt(ExternalBlob),
    'marksheet12' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'aadhaar' : IDL.Opt(ExternalBlob),
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'passCertificate' : IDL.Opt(ExternalBlob),
    'courseId' : CourseId,
  });
  const LeaveRequestInput = IDL.Record({
    'endDate' : IDL.Text,
    'startDate' : IDL.Text,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminCreateStudent' : IDL.Func(
        [IDL.Text, IDL.Text, StudentInput],
        [StudentView],
        [],
      ),
    'adminDeleteApplication' : IDL.Func(
        [IDL.Text, IDL.Text, ApplicationId],
        [IDL.Bool],
        [],
      ),
    'adminDeleteCertificate' : IDL.Func(
        [IDL.Text, IDL.Text, CertificateId],
        [IDL.Bool],
        [],
      ),
    'adminDeleteLeaveRequest' : IDL.Func(
        [IDL.Text, IDL.Text, LeaveRequestId],
        [IDL.Bool],
        [],
      ),
    'adminDeleteNotice' : IDL.Func(
        [IDL.Text, IDL.Text, NoticeId],
        [IDL.Bool],
        [],
      ),
    'adminDeleteStudent' : IDL.Func(
        [IDL.Text, IDL.Text, StudentId],
        [IDL.Bool],
        [],
      ),
    'adminGetStudent' : IDL.Func(
        [IDL.Text, IDL.Text, StudentId],
        [IDL.Opt(StudentView)],
        ['query'],
      ),
    'adminGetStudentAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, StudentId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'adminIssueCertificate' : IDL.Func(
        [IDL.Text, IDL.Text, StudentId],
        [Certificate],
        [],
      ),
    'adminListApplications' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AdmissionApplicationView)],
        [],
      ),
    'adminListCertificates' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Certificate)],
        ['query'],
      ),
    'adminListLeaveRequests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(LeaveRequestView)],
        ['query'],
      ),
    'adminListStudents' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(StudentView)],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminMarkAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, StudentId, IDL.Text, AttendanceStatus],
        [AttendanceRecord],
        [],
      ),
    'adminPostNotice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Notice],
        [],
      ),
    'adminRespondLeaveRequest' : IDL.Func(
        [IDL.Text, IDL.Text, LeaveRequestId, LeaveStatus],
        [IDL.Bool],
        [],
      ),
    'adminUpdateApplicationStatus' : IDL.Func(
        [IDL.Text, IDL.Text, ApplicationId, ApplicationStatus],
        [IDL.Bool],
        [],
      ),
    'adminUpdateStudent' : IDL.Func(
        [IDL.Text, IDL.Text, StudentId, StudentUpdateInput],
        [IDL.Bool],
        [],
      ),
    'adminUpdateStudentProfilePicture' : IDL.Func(
        [IDL.Text, IDL.Text, StudentId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'getApplication' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(AdmissionApplicationView)],
        ['query'],
      ),
    'getCertificate' : IDL.Func(
        [CertificateId],
        [IDL.Opt(Certificate)],
        ['query'],
      ),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
    'getMyAttendance' : IDL.Func(
        [StudentId],
        [
          IDL.Record({
            'records' : IDL.Vec(AttendanceRecord),
            'summary' : AttendanceSummary,
          }),
        ],
        ['query'],
      ),
    'getMyLeaveRequests' : IDL.Func(
        [StudentId],
        [IDL.Vec(LeaveRequestView)],
        ['query'],
      ),
    'getNotice' : IDL.Func([NoticeId], [IDL.Opt(Notice)], ['query']),
    'getStudentCertificates' : IDL.Func(
        [StudentId],
        [IDL.Vec(Certificate)],
        ['query'],
      ),
    'getStudentDashboard' : IDL.Func(
        [StudentId],
        [IDL.Opt(StudentView)],
        ['query'],
      ),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'listNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(StudentView)], []),
    'studentUpdateProfilePicture' : IDL.Func(
        [StudentId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'submitApplication' : IDL.Func(
        [ApplicationInput],
        [AdmissionApplicationView],
        [],
      ),
    'submitLeaveRequest' : IDL.Func(
        [StudentId, LeaveRequestInput],
        [LeaveRequestView],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };