/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdmissionApplicationView {
    id: ApplicationId;
    status: ApplicationStatus;
    marksheet10?: ExternalBlob;
    marksheet12?: ExternalBlob;
    name: string;
    submittedAt: Timestamp;
    aadhaar?: ExternalBlob;
    email: string;
    phone: string;
    photo?: ExternalBlob;
    passCertificate?: ExternalBlob;
    courseId: CourseId;
}
export type Timestamp = bigint;
export interface StudentView {
    id: StudentId;
    username: string;
    enrolled: boolean;
    applicationId?: ApplicationId;
    name: string;
    createdAt: Timestamp;
    email: string;
    phone: string;
    profilePicture?: string;
    courseId: CourseId;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface StudentInput {
    username: string;
    applicationId?: ApplicationId;
    password: string;
    name: string;
    email: string;
    phone: string;
    courseId: CourseId;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface StudentUpdateInput {
    enrolled?: boolean;
    name?: string;
    email?: string;
    phone?: string;
    courseId?: CourseId;
}
export type CertificateId = bigint;
export type StudentId = bigint;
export interface AttendanceSummary {
    total: bigint;
    present: bigint;
    late: bigint;
    absent: bigint;
}
export interface LeaveRequestView {
    id: LeaveRequestId;
    studentId: StudentId;
    endDate: string;
    leaveStatus: LeaveStatus;
    submittedAt: Timestamp;
    respondedAt?: Timestamp;
    startDate: string;
    reason: string;
}
export type LeaveRequestId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface LeaveRequestInput {
    endDate: string;
    startDate: string;
    reason: string;
}
export interface Course {
    id: CourseId;
    name: string;
    durationMonths: bigint;
    description: string;
    benefits: Array<string>;
}
export type AttendanceId = bigint;
export interface Notice {
    id: NoticeId;
    title: string;
    postedAt: Timestamp;
    content: string;
}
export type CourseId = string;
export interface ApplicationInput {
    marksheet10?: ExternalBlob;
    marksheet12?: ExternalBlob;
    name: string;
    aadhaar?: ExternalBlob;
    email: string;
    phone: string;
    photo?: ExternalBlob;
    passCertificate?: ExternalBlob;
    courseId: CourseId;
}
export interface AttendanceRecord {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
    markedAt: Timestamp;
}
export type NoticeId = bigint;
export interface Certificate {
    id: CertificateId;
    studentId: StudentId;
    studentName: string;
    issuedAt: Timestamp;
    courseName: string;
    certificateCode: string;
    courseId: CourseId;
}
export type ApplicationId = bigint;
export enum AttendanceStatus {
    present = "present",
    late = "late",
    absent = "absent"
}
export enum LeaveStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    adminCreateStudent(loginId: string, password: string, input: StudentInput): Promise<StudentView>;
    adminDeleteApplication(loginId: string, password: string, applicationId: ApplicationId): Promise<boolean>;
    adminDeleteCertificate(loginId: string, password: string, certificateId: CertificateId): Promise<boolean>;
    adminDeleteLeaveRequest(loginId: string, password: string, id: LeaveRequestId): Promise<boolean>;
    adminDeleteNotice(loginId: string, password: string, id: NoticeId): Promise<boolean>;
    adminDeleteStudent(loginId: string, password: string, studentId: StudentId): Promise<boolean>;
    adminGetStudent(loginId: string, password: string, id: StudentId): Promise<StudentView | null>;
    adminGetStudentAttendance(loginId: string, password: string, studentId: StudentId): Promise<Array<AttendanceRecord>>;
    adminIssueCertificate(loginId: string, password: string, studentId: StudentId): Promise<Certificate>;
    adminListApplications(loginId: string, password: string): Promise<Array<AdmissionApplicationView>>;
    adminListCertificates(loginId: string, password: string): Promise<Array<Certificate>>;
    adminListLeaveRequests(loginId: string, password: string): Promise<Array<LeaveRequestView>>;
    adminListStudents(loginId: string, password: string): Promise<Array<StudentView>>;
    adminLogin(loginId: string, password: string): Promise<boolean>;
    adminMarkAttendance(loginId: string, password: string, studentId: StudentId, date: string, status: AttendanceStatus): Promise<AttendanceRecord>;
    adminPostNotice(loginId: string, password: string, title: string, content: string): Promise<Notice>;
    adminRespondLeaveRequest(loginId: string, password: string, id: LeaveRequestId, status: LeaveStatus): Promise<boolean>;
    adminUpdateApplicationStatus(loginId: string, password: string, id: ApplicationId, status: ApplicationStatus): Promise<boolean>;
    adminUpdateStudent(loginId: string, password: string, id: StudentId, input: StudentUpdateInput): Promise<boolean>;
    adminUpdateStudentProfilePicture(loginId: string, password: string, studentId: StudentId, pictureData: string): Promise<boolean>;
    getApplication(id: ApplicationId): Promise<AdmissionApplicationView | null>;
    getCertificate(id: CertificateId): Promise<Certificate | null>;
    getCourse(id: string): Promise<Course | null>;
    getMyAttendance(studentId: StudentId): Promise<{
        records: Array<AttendanceRecord>;
        summary: AttendanceSummary;
    }>;
    getMyLeaveRequests(studentId: StudentId): Promise<Array<LeaveRequestView>>;
    getNotice(id: NoticeId): Promise<Notice | null>;
    getStudentCertificates(studentId: StudentId): Promise<Array<Certificate>>;
    getStudentDashboard(id: StudentId): Promise<StudentView | null>;
    listCourses(): Promise<Array<Course>>;
    listNotices(): Promise<Array<Notice>>;
    studentLogin(username: string, password: string): Promise<StudentView | null>;
    studentUpdateProfilePicture(studentId: StudentId, pictureData: string): Promise<boolean>;
    submitApplication(input: ApplicationInput): Promise<AdmissionApplicationView>;
    submitLeaveRequest(studentId: StudentId, input: LeaveRequestInput): Promise<LeaveRequestView>;
}
import type { AdmissionApplicationView as _AdmissionApplicationView, ApplicationId as _ApplicationId, ApplicationInput as _ApplicationInput, ApplicationStatus as _ApplicationStatus, AttendanceId as _AttendanceId, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, AttendanceSummary as _AttendanceSummary, Certificate as _Certificate, Course as _Course, CourseId as _CourseId, ExternalBlob as _ExternalBlob, LeaveRequestId as _LeaveRequestId, LeaveRequestView as _LeaveRequestView, LeaveStatus as _LeaveStatus, Notice as _Notice, StudentId as _StudentId, StudentInput as _StudentInput, StudentUpdateInput as _StudentUpdateInput, StudentView as _StudentView, Timestamp as _Timestamp, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async adminCreateStudent(arg0: string, arg1: string, arg2: StudentInput): Promise<StudentView> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateStudent(arg0, arg1, to_candid_StudentInput_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_StudentView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateStudent(arg0, arg1, to_candid_StudentInput_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_StudentView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteApplication(arg0: string, arg1: string, arg2: ApplicationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteApplication(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteApplication(arg0, arg1, arg2);
            return result;
        }
    }
    async adminDeleteCertificate(arg0: string, arg1: string, arg2: CertificateId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteCertificate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteCertificate(arg0, arg1, arg2);
            return result;
        }
    }
    async adminDeleteLeaveRequest(arg0: string, arg1: string, arg2: LeaveRequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteLeaveRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteLeaveRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async adminDeleteNotice(arg0: string, arg1: string, arg2: NoticeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteNotice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteNotice(arg0, arg1, arg2);
            return result;
        }
    }
    async adminDeleteStudent(arg0: string, arg1: string, arg2: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteStudent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteStudent(arg0, arg1, arg2);
            return result;
        }
    }
    async adminGetStudent(arg0: string, arg1: string, arg2: StudentId): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStudent(arg0, arg1, arg2);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStudent(arg0, arg1, arg2);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetStudentAttendance(arg0: string, arg1: string, arg2: StudentId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStudentAttendance(arg0, arg1, arg2);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStudentAttendance(arg0, arg1, arg2);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminIssueCertificate(arg0: string, arg1: string, arg2: StudentId): Promise<Certificate> {
        if (this.processError) {
            try {
                const result = await this.actor.adminIssueCertificate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminIssueCertificate(arg0, arg1, arg2);
            return result;
        }
    }
    async adminListApplications(arg0: string, arg1: string): Promise<Array<AdmissionApplicationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListApplications(arg0, arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListApplications(arg0, arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListCertificates(arg0: string, arg1: string): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListCertificates(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListCertificates(arg0, arg1);
            return result;
        }
    }
    async adminListLeaveRequests(arg0: string, arg1: string): Promise<Array<LeaveRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListLeaveRequests(arg0, arg1);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListLeaveRequests(arg0, arg1);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListStudents(arg0: string, arg1: string): Promise<Array<StudentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListStudents(arg0, arg1);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListStudents(arg0, arg1);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async adminMarkAttendance(arg0: string, arg1: string, arg2: StudentId, arg3: string, arg4: AttendanceStatus): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.adminMarkAttendance(arg0, arg1, arg2, arg3, to_candid_AttendanceStatus_n33(this._uploadFile, this._downloadFile, arg4));
                return from_candid_AttendanceRecord_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminMarkAttendance(arg0, arg1, arg2, arg3, to_candid_AttendanceStatus_n33(this._uploadFile, this._downloadFile, arg4));
            return from_candid_AttendanceRecord_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminPostNotice(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.adminPostNotice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminPostNotice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminRespondLeaveRequest(arg0: string, arg1: string, arg2: LeaveRequestId, arg3: LeaveStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRespondLeaveRequest(arg0, arg1, arg2, to_candid_LeaveStatus_n35(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRespondLeaveRequest(arg0, arg1, arg2, to_candid_LeaveStatus_n35(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async adminUpdateApplicationStatus(arg0: string, arg1: string, arg2: ApplicationId, arg3: ApplicationStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateApplicationStatus(arg0, arg1, arg2, to_candid_ApplicationStatus_n37(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateApplicationStatus(arg0, arg1, arg2, to_candid_ApplicationStatus_n37(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async adminUpdateStudent(arg0: string, arg1: string, arg2: StudentId, arg3: StudentUpdateInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateStudent(arg0, arg1, arg2, to_candid_StudentUpdateInput_n38(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateStudent(arg0, arg1, arg2, to_candid_StudentUpdateInput_n38(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async adminUpdateStudentProfilePicture(arg0: string, arg1: string, arg2: StudentId, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateStudentProfilePicture(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateStudentProfilePicture(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getApplication(arg0: ApplicationId): Promise<AdmissionApplicationView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplication(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplication(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificate(arg0: CertificateId): Promise<Certificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificate(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificate(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: string): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAttendance(arg0: StudentId): Promise<{
        records: Array<AttendanceRecord>;
        summary: AttendanceSummary;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttendance(arg0);
                return from_candid_record_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttendance(arg0);
            return from_candid_record_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLeaveRequests(arg0: StudentId): Promise<Array<LeaveRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLeaveRequests(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLeaveRequests(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotice(arg0: NoticeId): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotice(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotice(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentCertificates(arg0: StudentId): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentCertificates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentCertificates(arg0);
            return result;
        }
    }
    async getStudentDashboard(arg0: StudentId): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentDashboard(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentDashboard(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return result;
        }
    }
    async listNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotices();
            return result;
        }
    }
    async studentLogin(arg0: string, arg1: string): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.studentLogin(arg0, arg1);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.studentLogin(arg0, arg1);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async studentUpdateProfilePicture(arg0: StudentId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.studentUpdateProfilePicture(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.studentUpdateProfilePicture(arg0, arg1);
            return result;
        }
    }
    async submitApplication(arg0: ApplicationInput): Promise<AdmissionApplicationView> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(await to_candid_ApplicationInput_n45(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdmissionApplicationView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(await to_candid_ApplicationInput_n45(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdmissionApplicationView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLeaveRequest(arg0: StudentId, arg1: LeaveRequestInput): Promise<LeaveRequestView> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeaveRequest(arg0, arg1);
                return from_candid_LeaveRequestView_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeaveRequest(arg0, arg1);
            return from_candid_LeaveRequestView_n28(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_AdmissionApplicationView_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdmissionApplicationView): Promise<AdmissionApplicationView> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LeaveRequestView_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveRequestView): LeaveRequestView {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveStatus): LeaveStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_StudentView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentView): StudentView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApplicationId]): ApplicationId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentView]): StudentView | null {
    return value.length === 0 ? null : from_candid_StudentView_n10(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdmissionApplicationView]): Promise<AdmissionApplicationView | null> {
    return value.length === 0 ? null : await from_candid_AdmissionApplicationView_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Certificate]): Certificate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Notice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    username: string;
    enrolled: boolean;
    applicationId: [] | [_ApplicationId];
    name: string;
    createdAt: _Timestamp;
    email: string;
    phone: string;
    profilePicture: [] | [string];
    courseId: _CourseId;
}): {
    id: StudentId;
    username: string;
    enrolled: boolean;
    applicationId?: ApplicationId;
    name: string;
    createdAt: Timestamp;
    email: string;
    phone: string;
    profilePicture?: string;
    courseId: CourseId;
} {
    return {
        id: value.id,
        username: value.username,
        enrolled: value.enrolled,
        applicationId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.applicationId)),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        phone: value.phone,
        profilePicture: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.profilePicture)),
        courseId: value.courseId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: string;
    markedAt: _Timestamp;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: string;
    markedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n18(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        markedAt: value.markedAt
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ApplicationId;
    status: _ApplicationStatus;
    marksheet10: [] | [_ExternalBlob];
    marksheet12: [] | [_ExternalBlob];
    name: string;
    submittedAt: _Timestamp;
    aadhaar: [] | [_ExternalBlob];
    email: string;
    phone: string;
    photo: [] | [_ExternalBlob];
    passCertificate: [] | [_ExternalBlob];
    courseId: _CourseId;
}): Promise<{
    id: ApplicationId;
    status: ApplicationStatus;
    marksheet10?: ExternalBlob;
    marksheet12?: ExternalBlob;
    name: string;
    submittedAt: Timestamp;
    aadhaar?: ExternalBlob;
    email: string;
    phone: string;
    photo?: ExternalBlob;
    passCertificate?: ExternalBlob;
    courseId: CourseId;
}> {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n23(_uploadFile, _downloadFile, value.status),
        marksheet10: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.marksheet10)),
        marksheet12: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.marksheet12)),
        name: value.name,
        submittedAt: value.submittedAt,
        aadhaar: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.aadhaar)),
        email: value.email,
        phone: value.phone,
        photo: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.photo)),
        passCertificate: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.passCertificate)),
        courseId: value.courseId
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LeaveRequestId;
    studentId: _StudentId;
    endDate: string;
    leaveStatus: _LeaveStatus;
    submittedAt: _Timestamp;
    respondedAt: [] | [_Timestamp];
    startDate: string;
    reason: string;
}): {
    id: LeaveRequestId;
    studentId: StudentId;
    endDate: string;
    leaveStatus: LeaveStatus;
    submittedAt: Timestamp;
    respondedAt?: Timestamp;
    startDate: string;
    reason: string;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        endDate: value.endDate,
        leaveStatus: from_candid_LeaveStatus_n30(_uploadFile, _downloadFile, value.leaveStatus),
        submittedAt: value.submittedAt,
        respondedAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.respondedAt)),
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    records: Array<_AttendanceRecord>;
    summary: _AttendanceSummary;
}): {
    records: Array<AttendanceRecord>;
    summary: AttendanceSummary;
} {
    return {
        records: from_candid_vec_n15(_uploadFile, _downloadFile, value.records),
        summary: value.summary
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): LeaveStatus {
    return "pending" in value ? LeaveStatus.pending : "approved" in value ? LeaveStatus.approved : "rejected" in value ? LeaveStatus.rejected : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdmissionApplicationView>): Promise<Array<AdmissionApplicationView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AdmissionApplicationView_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaveRequestView>): Array<LeaveRequestView> {
    return value.map((x)=>from_candid_LeaveRequestView_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentView>): Array<StudentView> {
    return value.map((x)=>from_candid_StudentView_n10(_uploadFile, _downloadFile, x));
}
async function to_candid_ApplicationInput_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationInput): Promise<_ApplicationInput> {
    return await to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LeaveStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): _LeaveStatus {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_StudentInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentInput): _StudentInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_StudentUpdateInput_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentUpdateInput): _StudentUpdateInput {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enrolled?: boolean;
    name?: string;
    email?: string;
    phone?: string;
    courseId?: CourseId;
}): {
    enrolled: [] | [boolean];
    name: [] | [string];
    email: [] | [string];
    phone: [] | [string];
    courseId: [] | [_CourseId];
} {
    return {
        enrolled: value.enrolled ? candid_some(value.enrolled) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        courseId: value.courseId ? candid_some(value.courseId) : candid_none()
    };
}
async function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marksheet10?: ExternalBlob;
    marksheet12?: ExternalBlob;
    name: string;
    aadhaar?: ExternalBlob;
    email: string;
    phone: string;
    photo?: ExternalBlob;
    passCertificate?: ExternalBlob;
    courseId: CourseId;
}): Promise<{
    marksheet10: [] | [_ExternalBlob];
    marksheet12: [] | [_ExternalBlob];
    name: string;
    aadhaar: [] | [_ExternalBlob];
    email: string;
    phone: string;
    photo: [] | [_ExternalBlob];
    passCertificate: [] | [_ExternalBlob];
    courseId: _CourseId;
}> {
    return {
        marksheet10: value.marksheet10 ? candid_some(await to_candid_ExternalBlob_n47(_uploadFile, _downloadFile, value.marksheet10)) : candid_none(),
        marksheet12: value.marksheet12 ? candid_some(await to_candid_ExternalBlob_n47(_uploadFile, _downloadFile, value.marksheet12)) : candid_none(),
        name: value.name,
        aadhaar: value.aadhaar ? candid_some(await to_candid_ExternalBlob_n47(_uploadFile, _downloadFile, value.aadhaar)) : candid_none(),
        email: value.email,
        phone: value.phone,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n47(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        passCertificate: value.passCertificate ? candid_some(await to_candid_ExternalBlob_n47(_uploadFile, _downloadFile, value.passCertificate)) : candid_none(),
        courseId: value.courseId
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    applicationId?: ApplicationId;
    password: string;
    name: string;
    email: string;
    phone: string;
    courseId: CourseId;
}): {
    username: string;
    applicationId: [] | [_ApplicationId];
    password: string;
    name: string;
    email: string;
    phone: string;
    courseId: _CourseId;
} {
    return {
        username: value.username,
        applicationId: value.applicationId ? candid_some(value.applicationId) : candid_none(),
        password: value.password,
        name: value.name,
        email: value.email,
        phone: value.phone,
        courseId: value.courseId
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.late ? {
        late: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == LeaveStatus.pending ? {
        pending: null
    } : value == LeaveStatus.approved ? {
        approved: null
    } : value == LeaveStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
